[package]
name = "asset-preprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
earcutr = "0.5.0"
geo = "0.32"
itertools = "0.14"
ordered-float = "5.0"
renderer-types = { path = "../renderer-types/", features = ["shapefile"] }
shapefile = "0.7"
